#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'
#
#           Reusable services for docker compose
#
#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'
version: "3.9"

services:
  # Service that contains the whole project
  #
  # It requires the PACKAGE argument that specifies
  # the target package it should build (e.g. @layerzerolabs/utils-evm-hardhat)
  project:
    build:
      context: .
      target: development
    # We'll provide a single testing MNEMONIC for the project so that the test EVM nodes
    # account are in sync with the hardhat accounts
    environment:
      - MNEMONIC=${MNEMONIC}
    logging:
      driver: local
      options:
        max-size: "5m"
        compress: "false"

  # EVM node for testing purposes
  evm-node:
    extends:
      service: project
    build:
      target: evm-node
    command: anvil --mnemonic "$MNEMONIC" --accounts 40 --host 0.0.0.0
